---
- hosts: docker-manager-first
  name: Managers leave the swarm
  remote_user: {{ username }}
  become: yes
  become_user: {{ username }}
  roles:
   - docker-swarm-leave

- hosts: workers
  name: Workers leave the swarm
  remote_user: {{ username }}
  become: yes
  become_user: {{ username }}
  roles:
   - docker-node-leave
