---
- name: Run commands for docker swarm
  hosts: docker-manager-first
  remote_user: {{username}}
  become: yes
  become_user: {{username}}
  roles:
   - docker-swarm-init

  hosts: workers
  remote_user: {{username}}
  become: yes
  become_user: {{username}}
  roles:
   - docker-join-workers
