---
- hosts: docker-manager-first
  name: Initialize docker swarm
  remote_user: {{ username }}
  become: yes
  become_user: {{ username }}
  roles:
   - docker-swarm-init

- hosts: workers
  name: Join workers in swarm
  remote_user: {{ username }}
  become: yes
  become_user: {{ username }}
  roles:
   - docker-join-workers

- hosts: docker-manager-first
  name: Add label in nodes of Swarm
  remote_user: {{ username }}
  become: yes
  become_user: {{ username }}
  roles:
   - docker-add-labels




